language: python

python:
    - 3.8
    - 3.7
    - 3.6

branches:
    only:
        - main
        - hu1

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt



before_script:
    - "flake8 codebase"

script:
    - coverage run -m unittest discover

after_success:
    - coverage report
    - coveralls